### PR TITLE
Use reportTitle in the check name to support matrix builds

### PR DESCRIPTION
**Pull request by jasonleenaylor**
Addresses issue #15

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
Any comments or objections @paulpach @Boychenko 
Or is this action not really being maintained. :(

**Comment by Boychenko** [comment]
@jasonleenaylor I'm not a maintainer of this action. I've done only a tiny improvement. I hope @paulpach can help you

**Comment by jasonleenaylor** [comment]
@paulpach I guess this project is no longer maintained. :-(

**Comment by paulpach** [comment]
Jason,  the PR changes indentation on all files,  what did actually change?

**Pull request closed without merging**
